version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:3.2.1
    ports:
      - 9870:9870
    volumes:
      - hadoop-namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test

  datanode:
    image: bde2020/hadoop-datanode:3.2.1
    ports:
      - 9864:9864
    volumes:
      - hadoop-datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
  
  resourcemanager:
    image: bde2020/hadoop-resourcemanager:3.2.1
    ports:
      - 8088:8088
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864"

  nodemanager:
    image: bde2020/hadoop-nodemanager:3.2.1
    ports:
      - 8042:8042
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 resourcemanager:8088"
  
  historyserver:
    image: bde2020/hadoop-historyserver:3.2.1
    ports:
      - 8188:8188    
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      - hadoop-historyserver:/hadoop/yarn/timeline
  
volumes:
  hadoop-namenode:
  hadoop-datanode:
  hadoop-historyserver:
